### PR TITLE
Added push and clientbuffer modules.

### PR DESCRIPTION
**Pull request by br00tal**
This PR replaces #18 since it adds the 'push' module in addition to the 'clientbuffer' module.

Please take a look at this PR and see if it meets your standards.  The 'push' module would be great, as #18 suggests, but since that wasn't merged at all yet, I included it in this PR too, since I would like that functionality in addition to the 'clientbuffer' module, also included in this PR.

The 'clientbuffer' module allows you to specify separate buffers for different clients, which helps organize and send appropriate buffers to clients connecting and disconnecting at different times. Without this module, by default ZNC will only send the buffer to the first client to connect since last disconnect.  Any additional client connections won't receive any buffered messages if the first client is still connected. This module provides a way to deal with that.

Thanks for all your work. This is a fantastic project.

### CODE REVIEW

**Comment by br00tal** [comment]
Any chance someone can look at this? I use it everyday without issues.

**Comment by nicoulaj** [comment]
@j0nnymoe did you get a chance to take a look at this one ? (sorry for being pushy, you said on discord you would take a look)

**Comment by thelamer** [comment]
jenkins test this please

**Comment by thelamer** [comment]
Merging as the team voted yes to pulling in these third party libraries.

**Pull request merged**
